WorldName: 'Battle'

BuildEdge1X: 5
BuildEdge1Z: 5

BuildEdge2X: 7
BuildEdge2Z: 10


BlueSpawnX: 6
BlueSpawnY: 5
BlueSpawnZ: 6

RedSpawnX: -6
RedSpawnY: 5
RedSpawnZ: -6

SpectatorSpawnX: 10
SpectatorSpawnY: 10
SpectatorSpawnZ: 0