WorldName: Medieval

BuildEdge1X: 0
BuildEdge1Z: 0

BuildEdge2X: -50
BuildEdge2Z: 49

BlueSpawnX: 21.5
BlueSpawnY: 69
BlueSpawnZ: 9.5

RedSpawnX: -71.5
RedSpawnY: 70
RedSpawnZ: 40.5

SpectatorSpawnX: -25.5
SpectatorSpawnY: 115
SpectatorSpawnZ: 31.5