BlueEdge1X: 5
BlueEdge1Z: 5

BlueEdge2X: 7
BlueEdge2Z: 10

RedEdge1X: -5
RedEdge1Z: -5

RedEdge2X: -7
RedEdge2Z: -10

BlueSpawnX: 6
BlueSpawnY: 5
BlueSpawnZ: 6

RedSpawnX: -6
RedSpawnY: 5
RedSpawnZ: -6

SpectatorSpawnX: 10
SpectatorSpawnY: 10
SpectatorSpawnZ: 0